{{- if and .Values.tls.enabled .Values.certManager.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "app.fullname" . }}-wildcard
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  secretName: {{ include "app.tlsSecretName" . }}
  issuerRef:
    kind: {{ .Values.certManager.issuerRef.kind }}
    name: {{ .Values.certManager.issuerRef.name }}
  dnsNames:
    - {{ .Values.baseDomain }}
    - "*.{{ .Values.baseDomain }}"
{{- end }}
